### ISSUE TITLE
Really weird behavior with SMILES and hierarchical queries without code system

### ISSUE THREAD

**Issue by torstees** [ncpi-fhir/ncpi-fhir-platform-evaluation#23]
In the browser, the following query just returns an error stating that 'value as CodeableConcept' is an unknown child name. However, when performed in the test suite, it fails over and over again until a max failure count is exceeded (this may actually just be the ncpi fhir utility trying again and again). Anyway, it causes the test to run for a crazy long time. As such, I've just put an assertion until we check with SMILEs to decide if it's a known error. The same query works if you provide the system first:

Observation?value-concept:below=PRN

FWIW, this isn't a valid check if there are Observations coded with PRN. That seems unnecessary given that we can query for them like this...assuming it works properly and the test data only has MTH or FTH.

**Comment by RobertJCarroll** [comment]
I think the system is actually required, which makes sense given a code may appear in different systems and disambiguation is a problem.
From https://www.hl7.org/fhir/search.html#token :

> :below  the search parameter is a concept with the form [system]|[code], and the search parameter tests whether the coding in a resource is subsumed by the specified search code. For example, the coding in the resource has an is-a relationship with the 
search concept, and this includes the coding itself.

**Comment by torstees** [comment]
Good catch. Will remove that test case entirely, since it is a non-sense test.
